apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business
  template:
    metadata:
      labels:
        app: business
    spec:
      containers:
        - name: business
          image: besamly2018/sept-business
          env:
              - name: NATS_CLIENT_ID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NATS_URL
                value: 'http://nats-srv:4222'
              - name: NATS_CLUSTER_ID
                value: "sept"
              - name: JWT_KEY
                value: "sam"
          
---
apiVersion: v1
kind: Service
metadata:
  name: business-srv
spec:
  selector:
    app: business
  ports:
    - name: business
      protocol: TCP
      port: 3000
      targetPort: 3000
