version: 2.1

jobs:
  auth-backend-test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: cd auth && npm install
      - run:
          name: Run test
          command: cd auth && npm test

  business-backend-test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: cd business && npm install
      - run:
          name: Run test
          command: cd business && npm test

  auth-build-image:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Build image
          command: cd auth && docker build -t besamly2018/sept-auth .
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Docker image push
          command: docker push besamly2018/sept-auth

  business-build-image:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Build image
          command: cd business && docker build -t besamly2018/sept-business .
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Docker image push
          command: docker push besamly2018/sept-business

  deploy-to-cluster:
    docker:
      - image: digitalocean/action-doctl@v2
    steps:
      - checkout
      - run:
          name: Access to digital ocean context
          command: doctl auth init --access-token $DIGITALOCEAN_ACCESS_TOKEN
      - run:
          name: Apply infra config
          command: kubectl apply -f infra

workflows:
  automated-testing:
    jobs:
      - auth-backend-test:
          context: sept
          filters:
            branches:
              ignore:
                - master
      - business-backend-test:
          context: sept
          filters:
            branches:
              ignore:
                - master
      - auth-build-image:
          context: sept
          filters:
            branches:
              ignore:
                - master
      - business-build-image:
          context: sept
          filters:
            branches:
              ignore:
                - master
      - deploy-to-cluster:
          context: sept
          filters:
            branches:
              ignore:
                - master
